# Generated by Django 5.0.6 on 2024-07-07 19:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organisation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(default=api.models.generate_org_id, editable=False, max_length=10, unique=True),
        ),
    ]
